import os
from typing import Literal
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from configs.llm import get_llm
from configs.models import PPT_TEST_MODEL

class PPTReviewDecision(BaseModel):
    status: Literal["approved", "needs_fix"]
    feedback: str = Field(description="Actionable feedback for the PPT agent if it needs fixing. Empty if approved.")
    score: float = Field(ge=0, le=10, description="Score from 0 to 10 evaluating the presentation quality and compliance.")

ppt_review_llm = get_llm(model=PPT_TEST_MODEL)
ppt_review_chain = ppt_review_llm.with_structured_output(PPTReviewDecision)

SYSTEM_PROMPT = """
You are the PPT Review Agent of OmniMindAI.

You are a senior presentation designer and quality assurance expert.
Your job is to review the presentation plan generated by the PPT Agent against the user's original request.

Review Criteria:
1. Did the agent include images if requested?
2. Are the selected slide layouts visually interesting (not just boring bullets)?
3. Does the design theme match the topic?
4. Are all user requirements (topic, audience, requested specific content) met?

Rules:
- If the presentation is good enough, set status to "approved".
- If the presentation lacks visuals, uses repetitive boring layouts, or misses user requirements, set status to "needs_fix" and provide very specific actionable feedback (e.g. "Use 'cards' layout on slide 3 instead of bullets, and add an image keyword").
- Be slightly lenient to avoid infinite loops, but strict on explicit user requirements.
"""

def ppt_test_agent(state):
    print("===== PPT Test Agent =====")
    
    # Initialize attempt counter if missing
    attempt = state.get("review_attempt", 0) + 1
    state["review_attempt"] = attempt

    try:
        final_response = state.get("final_response", {})
        if not final_response or final_response.get("type") == "error":
            # If there was an error in generation, force a retry
            return {
                "review_status": "needs_fix",
                "review_feedback": "The PPT generation failed with an error. Please try again and fix any code or formatting issues.",
                "review_score": 0.0,
                "review_attempt": attempt
            }
        
        # Extract the outline to show the reviewer
        outline = final_response.get("outline", [])
        theme = final_response.get("theme", "Unknown")
        slide_count = final_response.get("slide_count", 0)

        review_input = f"""
        User Request:
        {state["query"]}

        Generated Presentation Info:
        Theme: {theme}
        Slide Count: {slide_count}
        Outline & Layouts:
        {outline}

        Please evaluate if this structure meets the user's demands and design standards.
        """

        result = ppt_review_chain.invoke([
            SystemMessage(content=SYSTEM_PROMPT),
            HumanMessage(content=review_input)
        ])

        return {
            "review_status": result.status,
            "review_feedback": result.feedback,
            "review_score": result.score,
            "review_attempt": attempt
        }
        
    except Exception as e:
        print(f"PPT Test Agent Error: {e}")
        return {
            "review_status": "approved", # Fallback to approved if review fails to avoid breaking
            "review_feedback": f"Review failed: {str(e)}",
            "review_score": 5.0,
            "review_attempt": attempt
        }
