from typing import Literal
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from configs.llm import get_llm
from configs.models import REVIEW_MODEL
from utils.content import extract_text
import os

"""
REVIEW ATTEMPT SEMANTICS:
- 0 = Code generated initially, not yet reviewed.
- 1 = First review completed (if needs_fix, review_attempt set to 1).
- 2 = Second review completed (if needs_fix, review_attempt set to 2).
- 3 = Third review completed (if needs_fix, review_attempt set to 3 -> MAX_REVIEW_ATTEMPTS reached).
"""

MAX_REVIEW_ATTEMPTS = int(os.getenv("MAX_REVIEW_ATTEMPTS", 3))

class ReviewDecision(BaseModel):
    status: Literal[
        "approved",
        "needs_fix",
    ]
    feedback: str
    score: float = Field(
        ge=0,
        le=10,
    )

review_llm = get_llm(
    model=REVIEW_MODEL,
)

review_chain = review_llm.with_structured_output(
    ReviewDecision
)

SYSTEM_PROMPT = """
You are the Code Review Agent of OmniMindAI.

You are a senior software engineer responsible for reviewing code generated by the Coding Agent.

Your job is NOT to generate new code.

Your job is to review the generated solution and determine whether it is production-ready.

Review the code based on:
- Correctness
- Logic
- Edge cases
- Security
- Performance
- Readability
- Maintainability
- Best practices
- Error handling
- Code quality

Rules:
- Approve the solution if it is good enough.
- Do NOT request unnecessary changes.
- Only request revision when there are real issues.
- Your feedback must be specific and actionable.
- Do not rewrite the solution.
- Return ONLY valid JSON.
"""

def review_agent(state):
    print("\n===== Review Agent =====")

    current_attempt = state.get("review_attempt", 0)
    print(f"[REVIEW] Prior review attempts: {current_attempt}/{MAX_REVIEW_ATTEMPTS}")

    try:
        review_input = f"""
            User Request:
            {state['query']}
            
            Generated Solution:
            {extract_text(state.get('final_response', ''))}
            
            Review the generated solution carefully.
        """

        result = review_chain.invoke(
            [
                SystemMessage(content=SYSTEM_PROMPT),
                HumanMessage(content=review_input),
            ]
        )

        new_attempt = current_attempt + 1 if result.status == "needs_fix" else current_attempt

        response = {
            "review_status": result.status,
            "review_feedback": result.feedback,
            "review_score": result.score,
            "review_attempt": new_attempt,
        }

        print(f"[REVIEW] Status: {result.status}, Score: {result.score}, Feedback: '{result.feedback}'")
        print(f"[REVIEW] Updated review_attempt: {new_attempt}/{MAX_REVIEW_ATTEMPTS}")

        return response

    except Exception as e:
        print(f"[REVIEW] Error in Review Agent: {e}")

        return {
            "review_status": "approved",
            "review_feedback": f"Review bypassed due to error: {e}",
            "review_attempt": current_attempt,
        }