name: OmniMind AI Deployment 

on: 
  push: 
    branches: 
      - main

env: 
  AWS_REGION: ${{ secrets.AWS_REGION}}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID}}


jobs: 

  deploy-backend:
    runs-on: ubuntu-latest
    steps: 
      - name:  Checkout Repository
        uses: actions/checkout@v4
      
      - name: AWS configure 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_REGION}}

      - name: Login to ECR 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: build Gateway
        run : |
              docker build \
                -f backend/gateway/Dockerfile \
                -t omnimind-gateway backend/gateway
      
      - name: tag Gateway
        run: |
            docker tag omnimind-gateway:latest ${{ steps.login-ecr.outputs.registry }}/omnimind-gateway:latest

      - name: push Gateway
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/omnimind-gateway:latest 
      
      - name: build auth service
        run : |
              docker build \
                -f backend/services/auth/Dockerfile \
                -t omnimind-auth backend/services/auth

      - name: tag auth service
        run: |
            docker tag omnimind-auth:latest ${{ steps.login-ecr.outputs.registry }}/omnimind-auth:latest

      - name: push auth service
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/omnimind-auth:latest 

      - name: build chat service
        run : |
              docker build \
                -f backend/services/chat/Dockerfile \
                -t omnimind-chat backend/services/chat

      - name: tag chat service
        run: |
            docker tag omnimind-chat:latest ${{ steps.login-ecr.outputs.registry }}/omnimind-chat:latest

      - name: push chat service
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/omnimind-chat:latest 

      - name: build agent service
        run : |
              docker build \
                -f backend/services/agent/Dockerfile \
                -t omnimind-agent backend/services/agent

      - name: tag agent service
        run: |
            docker tag omnimind-agent:latest ${{ steps.login-ecr.outputs.registry }}/omnimind-agent:latest

      - name: push agent service
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/omnimind-agent:latest 
      
      - name: deploy gateway
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME}} \
            --service ${{ secrets.ECS_GATEWAY_SERVICE_NAME}} \
            --force-new-deployment
      
      - name: deploy auth service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME}} \
            --service ${{ secrets.ECS_AUTH_SERVICE_NAME}} \
            --force-new-deployment
      
      - name: deploy chat service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME}} \
            --service ${{ secrets.ECS_CHAT_SERVICE_NAME}} \
            --force-new-deployment
      
      - name: deploy agent service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME}} \
            --service ${{ secrets.ECS_AGENT_SERVICE_NAME}} \
            --force-new-deployment
      
      
  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build frontend
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        run: |
            cd frontend
            npm install
            npm run build

      - name: AWS configure 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_REGION}}

      - name: upload dist folder to s3
        run: |
            aws s3 sync \
            ./frontend/dist \
            s3://${{ secrets.S3_BUCKET_NAME}} \
            --delete
            
      - name: Invalid CloudeFront
        run: |
            aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDEFRONT_DISTRIBUTION_ID}} \
            --paths "/*"   